# DEPRECATED: Export agent no longer uses MinIO storage
# Content is stored directly in state and returned via API
# from app.agents.tools.storage_tools import put_text
from app.llm.provider import llm_call

EXPORT_SYSTEM_PROMPT = """You are a world-class Technical Documentation Specialist and Content Architect with expertise in creating professional, publication-ready documentation for software projects.

## YOUR EXPERTISE:
- Technical writing (IEEE, ISO documentation standards)
- Markdown/MDX advanced formatting
- Documentation-as-Code practices
- Information architecture
- Accessibility standards (WCAG)
- Multi-format export (PDF, HTML, Confluence, Notion)

## YOUR MISSION:
Transform raw project artifacts (requirements, diagrams, plans) into a polished, cohesive, and professional project documentation package ready for stakeholder distribution.

## CONSOLIDATION RULES:
1. **Consistent formatting** across all sections
2. **Cross-references** between related sections
3. **Executive summary** synthesizing all artifacts
4. **Table of contents** with anchor links
5. **Professional tone** suitable for C-level executives
6. **Version control metadata** (date, version, authors)

## OUTPUT FORMAT:

# [Project Name] - Complete Project Blueprint

> **Version:** 1.0.0  
> **Generated:** [Date]  
> **Status:** Ready for Review  
> **Confidentiality:** Internal Use Only

---

## Table of Contents

1. [Executive Summary](#executive-summary)
2. [Project Requirements](#project-requirements)
3. [System Architecture](#system-architecture)
4. [Project Plan & Timeline](#project-plan--timeline)
5. [Appendices](#appendices)

---

## 1. Executive Summary

### Vision Statement
[One paragraph capturing the essence of the project]

### Key Metrics at a Glance
| Metric | Value |
|--------|-------|
| Estimated Duration | X weeks |
| Team Size | X people |
| Budget Range | $XX,XXX - $YY,YYY |
| Risk Level | Low/Medium/High |

### Quick Links
- [Full Requirements](requirements.md)
- [Architecture Diagrams](diagrams.md)
- [Detailed Project Plan](plan.md)

---

## 2. Project Requirements
[Consolidated requirements section]

## 3. System Architecture  
[All diagrams with explanations]

## 4. Project Plan & Timeline
[Complete planning details]

---

## 5. Appendices

### A. Glossary
| Term | Definition |
|------|------------|

### B. Reference Documents
| Document | Link/Location |
|----------|---------------|

### C. Change Log
| Version | Date | Changes | Author |
|---------|------|---------|--------|
| 1.0.0 | [Date] | Initial release | AI Blueprint System |

---

**Document Classification:** Internal  
**Review Cycle:** Quarterly  
**Owner:** Project Management Office

---
*This document was automatically generated by the AI Blueprint System.*"""


async def consolidate_and_export(
    project_id: int,
    requirements_content: str,
    diagrams_content: str, 
    plan_content: str,
    project_name: str = "Project"
) -> str:
    """
    Consolidates all project artifacts into a unified, professional document.
    """
    prompt = f"""{EXPORT_SYSTEM_PROMPT}

---

## INPUT ARTIFACTS TO CONSOLIDATE:

### REQUIREMENTS DOCUMENT:
{requirements_content}

### DIAGRAMS:
{diagrams_content}

### PROJECT PLAN:
{plan_content}

---

Now, create a unified, professional project blueprint document that:
1. Synthesizes all the above into a cohesive narrative
2. Adds an executive summary highlighting key insights
3. Ensures consistent formatting throughout
4. Adds cross-references between sections
5. Is ready for immediate stakeholder distribution

Project Name: {project_name}
"""
    
    consolidated = await llm_call(prompt)
    return consolidated


async def export_markdown(project_id: int, content: str) -> str:
    """
    DEPRECATED: No longer exports to MinIO storage.
    Content is stored directly in state and returned via API.
    This function is kept for compatibility but returns empty string.
    """
    # return put_text(f"projects/{project_id}/exports", content)
    return ""  # No longer using MinIO


# JSON structured output for export
EXPORT_JSON_OUTPUT_STRUCTURE = """{
  "document": {
    "title": "E-Commerce Platform",
    "description": "Complete project blueprint for building a modern e-commerce platform",
    "overview": "This project aims to create a scalable, secure e-commerce platform with modern features including user authentication, product catalog, shopping cart, and payment processing.",
    "goals": [
      {
        "label": "User Experience",
        "description": "Create an intuitive and responsive shopping experience across all devices"
      },
      {
        "label": "Scalability",
        "description": "Build infrastructure that can handle 10,000+ concurrent users"
      },
      {
        "label": "Security",
        "description": "Implement industry-standard security practices for payment and data protection"
      }
    ],
    "scope_in": [
      {
        "label": "User Authentication",
        "description": "Registration, login, OAuth integration (Google, Facebook)"
      },
      {
        "label": "Product Catalog",
        "description": "Product listing, search, filtering, and detailed product pages"
      },
      {
        "label": "Shopping Cart",
        "description": "Add to cart, update quantities, checkout flow"
      },
      {
        "label": "Payment Processing",
        "description": "Integration with Stripe for credit card payments"
      }
    ],
    "scope_out": [
      {
        "label": "Mobile Apps",
        "description": "Native iOS/Android apps are not included in this phase"
      },
      {
        "label": "Inventory Management",
        "description": "Warehouse and stock management will be added in Phase 2"
      },
      {
        "label": "Multi-vendor Support",
        "description": "Marketplace features for multiple sellers not included"
      }
    ],
    "sections": [
      {
        "title": "Technical Architecture",
        "content": "The system follows a microservices architecture with separate services for authentication, catalog, cart, and payments.",
        "items": [
          {
            "label": "Frontend",
            "description": "React with Next.js for server-side rendering and optimal performance"
          },
          {
            "label": "Backend",
            "description": "Node.js with Express for API gateway, Python FastAPI for microservices"
          },
          {
            "label": "Database",
            "description": "PostgreSQL for relational data, Redis for caching and sessions"
          }
        ]
      },
      {
        "title": "Security Considerations",
        "content": "Security is a top priority with multiple layers of protection.",
        "items": [
          {
            "label": "Authentication",
            "description": "JWT tokens with refresh mechanism, OAuth 2.0 for social login"
          },
          {
            "label": "Data Protection",
            "description": "HTTPS only, encrypted database fields, GDPR compliance"
          },
          {
            "label": "Payment Security",
            "description": "PCI DSS compliant via Stripe, no card data stored locally"
          }
        ]
      }
    ]
  },
  "github_export": [
    {
      "repo_name": "ecommerce-frontend",
      "branch": "main",
      "content": "# E-Commerce Frontend\\n\\n## Setup\\n```bash\\nnpm install\\nnpm run dev\\n```\\n\\n## Dependencies\\n- Next.js 14\\n- React 18\\n- TailwindCSS\\n- Axios"
    },
    {
      "repo_name": "ecommerce-backend",
      "branch": "main",
      "content": "# E-Commerce Backend\\n\\n## Setup\\n```bash\\npip install -r requirements.txt\\nuvicorn main:app --reload\\n```\\n\\n## Dependencies\\n- FastAPI\\n- PostgreSQL\\n- Redis\\n- Stripe SDK"
    }
  ]
}"""


async def generate_export_json(idea: str, requirements: str, diagrams_json: str, planner_json: str) -> str:
    """
    Generates structured JSON output for project export documentation.
    Returns JSON string with document structure and GitHub export templates.
    """
    prompt = f"""You are a world-class Technical Documentation Specialist and Project Architect.

Your task is to analyze the project artifacts below and generate a comprehensive export document in JSON format.

## PROJECT IDEA:

{idea}

## REQUIREMENTS (Text):

{requirements}

## PLANNER DATA (JSON):

{planner_json}

---

## YOUR TASK:

Generate a complete project export document as a JSON object with the following structure:

1. **document**: Main documentation structure
   - **title**: Project name (concise, professional)
   - **description**: One-sentence project description
   - **overview**: 2-3 paragraph executive summary
   - **goals**: List of 3-5 key project goals with labels and descriptions
   - **scope_in**: List of features/requirements IN SCOPE (5-10 items)
   - **scope_out**: List of features/requirements OUT OF SCOPE (3-5 items)
   - **sections**: Additional documentation sections (Technical Architecture, Security, Deployment, etc.)

2. **github_export**: GitHub repository templates (1-3 repos)
   - **repo_name**: Repository name
   - **branch**: Default branch (usually "main")
   - **content**: README.md content with setup instructions, dependencies, and project structure

## GUIDELINES:

- Be SPECIFIC and ACTIONABLE in all descriptions
- Extract goals from requirements and planner data
- Define clear scope boundaries (what's included vs. excluded)
- Create realistic GitHub README templates with actual setup commands
- Use professional, technical language
- Ensure consistency with provided artifacts

## OUTPUT FORMAT:

Return ONLY valid JSON - no markdown, no code blocks, no explanations.

EXAMPLE STRUCTURE:
{EXPORT_JSON_OUTPUT_STRUCTURE}

Now generate the complete export document JSON for the project above. Be thorough, professional, and aligned with the provided artifacts."""
    
    return await llm_call(prompt)
