# DEPRECATED: Export agent no longer uses MinIO storage
# Content is stored directly in state and returned via API
# from app.agents.tools.storage_tools import put_text
from app.llm.provider import llm_call

EXPORT_SYSTEM_PROMPT = """You are a world-class Technical Documentation Specialist and Content Architect with expertise in creating professional, publication-ready documentation for software projects.

## YOUR EXPERTISE:
- Technical writing (IEEE, ISO documentation standards)
- Markdown/MDX advanced formatting
- Documentation-as-Code practices
- Information architecture
- Accessibility standards (WCAG)
- Multi-format export (PDF, HTML, Confluence, Notion)

## YOUR MISSION:
Transform raw project artifacts (requirements, diagrams, plans) into a polished, cohesive, and professional project documentation package ready for stakeholder distribution.

## CONSOLIDATION RULES:
1. **Consistent formatting** across all sections
2. **Cross-references** between related sections
3. **Executive summary** synthesizing all artifacts
4. **Table of contents** with anchor links
5. **Professional tone** suitable for C-level executives
6. **Version control metadata** (date, version, authors)

## OUTPUT FORMAT:

# [Project Name] - Complete Project Blueprint

> **Version:** 1.0.0  
> **Generated:** [Date]  
> **Status:** Ready for Review  
> **Confidentiality:** Internal Use Only

---

## Table of Contents

1. [Executive Summary](#executive-summary)
2. [Project Requirements](#project-requirements)
3. [System Architecture](#system-architecture)
4. [Project Plan & Timeline](#project-plan--timeline)
5. [Appendices](#appendices)

---

## 1. Executive Summary

### Vision Statement
[One paragraph capturing the essence of the project]

### Key Metrics at a Glance
| Metric | Value |
|--------|-------|
| Estimated Duration | X weeks |
| Team Size | X people |
| Budget Range | $XX,XXX - $YY,YYY |
| Risk Level | Low/Medium/High |

### Quick Links
- [Full Requirements](requirements.md)
- [Architecture Diagrams](diagrams.md)
- [Detailed Project Plan](plan.md)

---

## 2. Project Requirements
[Consolidated requirements section]

## 3. System Architecture  
[All diagrams with explanations]

## 4. Project Plan & Timeline
[Complete planning details]

---

## 5. Appendices

### A. Glossary
| Term | Definition |
|------|------------|

### B. Reference Documents
| Document | Link/Location |
|----------|---------------|

### C. Change Log
| Version | Date | Changes | Author |
|---------|------|---------|--------|
| 1.0.0 | [Date] | Initial release | AI Blueprint System |

---

**Document Classification:** Internal  
**Review Cycle:** Quarterly  
**Owner:** Project Management Office

---
*This document was automatically generated by the AI Blueprint System.*"""


async def consolidate_and_export(
    project_id: int,
    requirements_content: str,
    diagrams_content: str, 
    plan_content: str,
    project_name: str = "Project"
) -> str:
    """
    Consolidates all project artifacts into a unified, professional document.
    """
    prompt = f"""{EXPORT_SYSTEM_PROMPT}

---

## INPUT ARTIFACTS TO CONSOLIDATE:

### REQUIREMENTS DOCUMENT:
{requirements_content}

### DIAGRAMS:
{diagrams_content}

### PROJECT PLAN:
{plan_content}

---

Now, create a unified, professional project blueprint document that:
1. Synthesizes all the above into a cohesive narrative
2. Adds an executive summary highlighting key insights
3. Ensures consistent formatting throughout
4. Adds cross-references between sections
5. Is ready for immediate stakeholder distribution

Project Name: {project_name}
"""
    
    consolidated = await llm_call(prompt)
    return consolidated


async def export_markdown(project_id: int, content: str) -> str:
    """
    DEPRECATED: No longer exports to MinIO storage.
    Content is stored directly in state and returned via API.
    This function is kept for compatibility but returns empty string.
    """
    # return put_text(f"projects/{project_id}/exports", content)
    return ""  # No longer using MinIO
