from typing import TypedDict, Optional
from uuid import UUID


class BlueprintState(TypedDict):
    # Context
    project_id: UUID
    run_id: UUID
    idea: str

    # Project metadata (generated by metadata agent)
    project_name: Optional[str]
    project_description: Optional[str]

    # Outputs des agents (contenu texte brut - sans MinIO)
    problem_definition: Optional[str]
    functional_requirements: Optional[str]
    non_functional_requirements: Optional[str]
    architecture: Optional[str]
    uml_sequence: Optional[str]
    sprint_planning: Optional[str]

    # Contenu généré par les agents (texte brut pour frontend)
    requirements_content: Optional[str]      # Contenu requirements.md
    diagrams_content: Optional[str]          # Contenu diagrams.md
    diagrams_json_content: Optional[str]     # JSON React Flow pour frontend
    planner_content: Optional[str]           # Contenu plan.md
    export_content: Optional[str]            # Contenu final export.md

    # Final
    blueprint_markdown: Optional[str]
